GameStore.WebUI/Controllers/AdminController.cs
using System.Web.Mvc;
using GameStore.Domain.Abstract;
using GameStore.Domain.Entities;
using System.Linq;
using System.Web;



namespace GameStore.WebUI.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        IGameRepository repository;

        public AdminController(IGameRepository repo)
        {
            repository = repo;
        }

        public ViewResult Index()
        {
            return View(repository.Games);
        }
        public ViewResult Edit(int gameId)
        {
            Game game = repository.Games
                .FirstOrDefault(g => g.GameId == gameId);
            return View(game);
        }

        [HttpPost]
        public ActionResult Edit(Game game, HttpPostedFileBase image = null)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    game.ImageMimeType = image.ContentType;
                    game.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(game.ImageData, 0, image.ContentLength);
                }
                repository.SaveGame(game);
                TempData["message"] = string.Format("Зміни в грі \"{0}\" були збережені", game.Name);
                return RedirectToAction("Index");
            }
            else
            {
                return View(game);
            }
        }

        public ViewResult Create()
        {
            return View("Edit", new Game());
        }
        [HttpPost]
        public ActionResult Delete(int gameId)
        {
            Game deletedGame = repository.DeleteGame(gameId);
            if (deletedGame != null)
            {
                TempData["message"] = string.Format("Гра \"{0}\" була видалена",
                    deletedGame.Name);
            }
            return RedirectToAction("Index");
        }
    }
}

GameStore.WebUI/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GameStore.Domain.Abstract;
using GameStore.Domain.Entities;
using GameStore.WebUI.Models;

namespace GameStore.WebUI.Controllers
{
    public class GameController : Controller
    {
        private IGameRepository repository;
        public int pageSize = 4;

        public GameController(IGameRepository repo)
        {
            repository = repo;
        }

        public ViewResult List(string category, int page = 1)
        {
            GamesListViewModel model = new GamesListViewModel
            {
                Games = repository.Games
                    .Where(p => category == null || p.Category == category)
                    .OrderBy(game => game.GameId)
                    .Skip((page - 1) * pageSize)
                    .Take(pageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = category == null ?
                    repository.Games.Count() :
                    repository.Games.Where(game => game.Category == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }
        public FileContentResult GetImage(int gameId)
        {
            Game game = repository.Games
                .FirstOrDefault(g => g.GameId == gameId);

            if (game != null)
            {
                return File(game.ImageData, game.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

GameStore.WebUI/Views/Admin/Edit.cshtml
@model GameStore.Domain.Entities.Game

@{
    ViewBag.Title = "Адмін панель: редагування товару";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel">
    <div class="panel-heading">
        <h3>Редагування гри «@Model.Name»</h3>
    </div>

    @using (Html.BeginForm("Edit", "Admin",
        FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
<div class="panel-body">
    @Html.HiddenFor(m => m.GameId)
    @foreach (var property in ViewData.ModelMetadata.Properties)
    {
        switch (property.PropertyName)
        {
            case "GameId":
            case "ImageData":
            case "ImageMimeType":
                break;
            default:
                <div class="form-group">
                    <label>@(property.DisplayName ?? property.PropertyName)</label>
                    @if (property.PropertyName == "Description")
                    {
                        @Html.TextArea(property.PropertyName, null,
                            new { @class = "form-control", rows = 5 })
                    }
                    else
                    {
                        @Html.TextBox(property.PropertyName, null,
                            new { @class = "form-control" })
                    }
                    @Html.ValidationMessage(property.PropertyName)
                </div>
                break;
        }
    }
    <div class="form-group">
        <div style="position:relative;">
            <label>Зображення</label>
            <a class='btn' href='javascript:;'>
                Оберіть файл...
                <input type="file" name="Image" size="40"
                       style="position:absolute;z-index:2;top:0;
                                left:0;filter: alpha(opacity=0); opacity:0;
                                background-color:transparent;color:transparent;"
                       onchange='$("#upload-file-info").html($(this).val());'>
            </a>
            <span class='label label-info' id="upload-file-info"></span>
        </div>
        @if (Model.ImageData == null)
        {
            <div class="form-control-static">Немає зображення</div>
        }
        else
        {
            <img class="img-thumbnail" width="150" height="150"
                 src="@Url.Action("GetImage", "Game",
                        new { Model.GameId })" />
        }
    </div>
</div>
        <div class="panel-footer">
            <input type="submit" value="Зберегти" class="btn btn-primary" />
            @Html.ActionLink("Скасувати зміни та повернутися до списку", "Index", null, new
            {
                @class = "btn btn-default"
            })
        </div>
    }
</div>

GameStore.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<GameStore.Domain.Entities.Game>

@{
    ViewBag.Title = "Адмін панель: список товарів";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>Список ігор</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-right">ID</th>
                <th>Назва</th>
                <th class="text-right">Ціна</th>
                <th class="text-center">Дія</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-right">@item.GameId</td>
                    <td>@Html.ActionLink(item.Name, "Edit", new { item.GameId })</td>
                    <td class="text-right">@item.Price.ToString("# грн")</td>
                    <td class="text-center">
                        @using (Html.BeginForm("Delete", "Admin"))
                        {
                            @Html.Hidden("GameId", item.GameId)
                            <input type="submit"
                                   class="btn btn-default btn-xs"
                                   value="Видалити" />
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Добавити гру", "Create", null,
            new { @class = "btn btn-default" })
    </div>
</div>